### ISSUE TITLE
[Roadmap] - v1.0.1

### ISSUE THREAD

**Issue by alefesta** [k3ai/k3ai#32]
This is the planning issue to decide what we want to keep in the v1.0.1 milestone. A similar issue will be created for v1.0.2

Target Release Date **November 30th**

K3ai:

- [x] #11 Minimal support for WSL (docs included) - @alefesta - Moved to v1.0.2
- [x] #13 @alefesta 
- [x] #14 @alefesta 
- [x] #19 Minimal documentation to run K3ai as GH @burntcarrot 
- [x] #18 @burntcarrot 
- [x] #25 @burntcarrot 
- [x] #20 @alefesta  - Moved to v1.0.2

K3ai Plugins:
 
- [x] https://github.com/k3ai/plugins/issues/6 @alefesta 
- [x] https://github.com/k3ai/plugins/issues/7 @alefesta 

Bugs:
- [x] #41 

If you like to work on something assign yourself editing this issue or comment below
