### ISSUE TITLE
[Feature] List results based on User demand

### ISSUE THREAD

**Issue by alefesta** [k3ai/k3ai#8]
We should have a mature way to list various informations related to the actual usage of K3ai.
A minimum set should include:
- [x] List cluster type, plugins, and bundles available
- [x]  List registered clusters
- [x] List plugins installed by cluster
